//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMenuAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public Ad()
        {
            this.AdsResources = new HashSet<AdsResource>();
        }
    
        public int ID { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AdsResource> AdsResources { get; set; }
    }
}
