//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMenuAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemPhotos = new HashSet<ItemPhoto>();
            this.ItemRatings = new HashSet<ItemRating>();
            this.ItemReviews = new HashSet<ItemReview>();
        }
    
        public int ID { get; set; }
        public int SubCategoryID { get; set; }
        public string NameEN { get; set; }
        public string NameAR { get; set; }
        public string DescriptionEN { get; set; }
        public string DescriptionAR { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<bool> HasSideDishes { get; set; }
        public string ImageURL { get; set; }
        public byte[] BinaryContent { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual ICollection<ItemPhoto> ItemPhotos { get; set; }
        public virtual ICollection<ItemRating> ItemRatings { get; set; }
        public virtual ICollection<ItemReview> ItemReviews { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
