//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMenuAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemReview
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string ReviewAR { get; set; }
        public string ReviewEN { get; set; }
        public string GuestName { get; set; }
        public string GuestEmail { get; set; }
        public string GuestPhone { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
